version: "3.9"
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
    environment: 
      - CHOKIDAR_USEPOLLING=true # Enable polling for hot reloading on some systems
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000 #Example environment variable