version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
    depends_on:
      - api

  frontend:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.frontend
    ports:
      - '3000:80'
    volumes:
      - ./frontend:/app

  api:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.api
    ports:
      - '3001:3000'
    volumes:
      - ./api:/app
