version: "3.9"

services: 
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src:delegated # Bind mount the current directory (code) into the container's /app directory
#      - ./target:/app/target # Ensure /target directory is not overwritten (where build artifacts go)
      - ./target/classes:/app/target/classes:delegated
    ports:
      - "8080:8080" # Expose the backend app on port 8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev # Optional, for setting the dev profile
      - SPRING_DEVTOOLS_RESTART_ENABLED=true # Enable spring DevTools for hot reloading
      - JAVA_OPTS=-Dspring.devtools.restart.enabled=true -Dspring.devtools.livereload.enabled=true
    command: mvn spring-boot:run # Use Maven to start the app for hot reloading
    networks:
      - app_network
    depends_on:
      - mysql
    restart: unless-stopped
  
  mysql:
    image: mysql:8.0 # You can choose a specific version of MySQL
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_canteen_app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql # Persist MYSQL data between container restarts
    ports:
      - "3308:3306" # Expose MySQL on port 3308
    networks:
      - app_network

networks:
  app_network:
    driver: bridge


volumes:
  mysql-data:
    driver: local