# Use Node.js
FROM node:18

# Set working directory
WORKDIR /app

# Copy package files
COPY backend/express-service/package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY backend/express-service ./

# Expose port
EXPOSE 5000

# Start the API
CMD ["node", "server.js"]
